// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv2Gq1MSvpAwolN9QxvqmBrbFgXeg-bq4',
    appId: '1:722804346625:web:388efe1cf357030e2f9500',
    messagingSenderId: '722804346625',
    projectId: 'sigmaszwadron',
    authDomain: 'sigmaszwadron.firebaseapp.com',
    databaseURL: 'https://sigmaszwadron-default-rtdb.firebaseio.com',
    storageBucket: 'sigmaszwadron.firebasestorage.app',
    measurementId: 'G-S6G2HN472W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5IiPD0sAdRrKF_sETRXEV4Kms5bL8s2c',
    appId: '1:722804346625:android:cea3f3d553733ae02f9500',
    messagingSenderId: '722804346625',
    projectId: 'sigmaszwadron',
    databaseURL: 'https://sigmaszwadron-default-rtdb.firebaseio.com',
    storageBucket: 'sigmaszwadron.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyQrQg10RT3MeqlbL0V9yf2PAoD451r-0',
    appId: '1:722804346625:ios:655128c2b75a73912f9500',
    messagingSenderId: '722804346625',
    projectId: 'sigmaszwadron',
    databaseURL: 'https://sigmaszwadron-default-rtdb.firebaseio.com',
    storageBucket: 'sigmaszwadron.firebasestorage.app',
    iosBundleId: 'com.example.normalApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyQrQg10RT3MeqlbL0V9yf2PAoD451r-0',
    appId: '1:722804346625:ios:655128c2b75a73912f9500',
    messagingSenderId: '722804346625',
    projectId: 'sigmaszwadron',
    databaseURL: 'https://sigmaszwadron-default-rtdb.firebaseio.com',
    storageBucket: 'sigmaszwadron.firebasestorage.app',
    iosBundleId: 'com.example.normalApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-QuwWCUKNHLQe9jlwCturVDEeXkhiOxM',
    appId: '1:722804346625:web:7de5324904867c592f9500',
    messagingSenderId: '722804346625',
    projectId: 'sigmaszwadron',
    authDomain: 'sigmaszwadron.firebaseapp.com',
    databaseURL: 'https://sigmaszwadron-default-rtdb.firebaseio.com',
    storageBucket: 'sigmaszwadron.firebasestorage.app',
    measurementId: 'G-BRSHP82LB4',
  );
}
